version: "3.0"                     

services:

  emqx-wc:
      image: emqx/emqx:latest
      # volumes:
      #   - ./broker/plugins:/opt/emqx/etc/plugins
      #   - ../../proxy/certs/brokerwc.windowschannel.com.key:/opt/emqx/etc/certs/emqx.key
      #   - ../../proxy/certs/brokerwc.windowschannel.com.crt:/opt/emqx/etc/certs/emqx.crt
      #   - ../../proxy/certs/brokerwc.windowschannel.com.ca:/opt/emqx/etc/certs/emqx.ca
      environment:
        - EMQX_NAME=windowschannel
        - EMQX_HOST=administradorcanales.windowschannel.com
        # - EMQX_LISTENER__SSL__EXTERNAL__KEYFILE=etc/certs/emqx.key
        # - EMQX_LISTENER__SSL__EXTERNAL__CERTFILE=etc/certs/emqx.crt
        # - EMQX_LISTENER__SSL__EXTERNAL__CACERTFILE=etc/certs/emqx.ca
        # - EMQX_LISTENER__WSS__EXTERNAL__KEYFILE=etc/certs/emqx.key
        # - EMQX_LISTENER__WSS__EXTERNAL__CERTFILE=etc/certs/emqx.crt
        # - EMQX_LISTENER__WSS__EXTERNAL__CACERTFILE=etc/certs/emqx.ca
        - VIRTUAL_HOST=brokerwc.windowschannel.com
        - VIRTUAL_PORT=18083
        - EMQX_LOADED_PLUGINS=emqx_management,emqx_dashboard
      expose:
         - "18083"
      
      ports:
        - "1885:1883" # MQTT
        - "8885:8883" # MQTT/SSL
        - "7084:8083" # MQTT/WS
        - "8086:8084" # MQTT/WSS
        - "8081:8081" # api http
        - "8082:8082" # api https
        # - "18083:18083" # Dashboard

  web-ui:
    image: web-ui-dev
    container_name: container-web-ui-dev
    build:
      context: ./web-ui
      dockerfile: Dockerfile
    environment:
     - VIRTUAL_HOST=administradorcanales.windowschannel.com
     - VIRTUAL_PORT=8080
    volumes:
     - ./web-ui:/usr/src/app/my-app
     - /usr/src/app/my-app/node_modules
    expose:
     - "8080"

  nginx-server-rtmp:
    container_name: server-rtmp-nginx-dev
    build:
      context: ./server-rtmp-container
      dockerfile: Dockerfile
    volumes:
      - ./server-rtmp-container/nginx/nginx.conf:/usr/local/nginx/conf/nginx.conf
    ports:
      - 8090:8080
      - 1935:1935

  # nginx-web:
  #    image: nginx:1.19.0-alpine
  #    depends_on:
  #    - web-ui
  #    volumes:
  #    - ./web-ui/dist:/usr/share/nginx/html
  #    environment:
  #     - VIRTUAL_HOST= imbanaco.windowschannel.us #url 
  #    ports:
  #     - '8080:80'
          
networks:
  default:
    external:
      name: channels


