version: "3.0"                     

services:    
  web-ui:
    #Include variables for allow https
    image: web-ui-dev
    restart: always
    container_name: container-web-ui-dev
    build:
      context: ./web-ui
      dockerfile: Dockerfile
    environment:      
     - VIRTUAL_HOST=administradorcanales.windowschannel.com
     - LETSENCRYPT_HOST=administradorcanales.windowschannel.com
     - LETSENCRYPT_EMAIL=info@windowschannel.com
     - VIRTUAL_PORT=8080
    volumes:
     - ./web-ui:/usr/src/app/my-app
     - /usr/src/app/my-app/node_modules
    expose:
     - "8080"

  nginx-rtmp-winbox:
    container_name: server-rtmp-winbox
    restart: always
    build:
      context: ./server-rtmp-container
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=rtmpwindowschannelwinbox.windowschannel.com
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=rtmpwindowschannelwinbox.windowschannel.com
      - LETSENCRYPT_EMAIL=info@windowschannel.com
    volumes:
      - ./server-rtmp-container/nginx/nginx.conf:/usr/local/nginx/conf/nginx.conf
    ports:
      - 8080:8080
      - 1935:1935
  
  #Production
  # nginx-web:
  #    image: nginx:1.19.0-alpine
  #    depends_on:
  #    - web-ui
  #    volumes:
  #    - ./web-ui/dist:/usr/share/nginx/html
  #    environment:
  #     - VIRTUAL_HOST= imbanaco.windowschannel.us #url 
  #    ports:
  #     - '8080:80'
          
networks:
  default:
    external:
      name: channels


