version: "3.0"                     

services:    
  web-ui:
    #Include variables for allow https
    image: web-ui-dev
    restart: always
    container_name: web-ui-cmi
    build:
      context: ./web-ui
      dockerfile: Dockerfile
    environment:      
     - VIRTUAL_HOST=cmi.windowschannel.com
     - LETSENCRYPT_HOST=cmi.windowschannel.com
     - LETSENCRYPT_EMAIL=info@windowschannel.com
     - VIRTUAL_PORT=8080
    volumes:
     - ./web-ui:/usr/src/app/my-app
     - /usr/src/app/my-app/node_modules
    expose:
     - "8080"

  nginx-rtmp-winbox:
    restart: always
    build:
      context: ./server-rtmp-container
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=rtmpcmiinstitucional.windowschannel.us
      - LETSENCRYPT_HOST=rtmpcmiinstitucional.windowschannel.us
      - LETSENCRYPT_EMAIL=info@windowschannel.com
      - VIRTUAL_PORT=8010
    volumes:
      - ./server-rtmp-container/streamings/nginx-winbox/nginx.conf:/usr/local/nginx/conf/nginx.conf
    ports:
      - 1937:1935
      - 8010:8010

  nginx-rtmp-comercial:
    restart: always
    build:
      context: ./server-rtmp-container
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=rtmpcmicomercial.windowschannel.us
      - LETSENCRYPT_HOST=rtmpcmicomercial.windowschannel.us
      - LETSENCRYPT_EMAIL=info@windowschannel.com
      - VIRTUAL_PORT=8011
    volumes:
      - ./server-rtmp-container/streamings/nginx-comercial/nginx.conf:/usr/local/nginx/conf/nginx.conf
    ports:
      - 1938:1935
      - 8011:8011

  
  #Production
  # nginx-web:
  #    image: nginx:1.19.0-alpine
  #    depends_on:
  #    - web-ui
  #    volumes:
  #    - ./web-ui/dist:/usr/share/nginx/html
  #    environment:
  #     - VIRTUAL_HOST= imbanaco.windowschannel.us #url 
  #    ports:
  #     - '8080:80'
          
networks:
  default:
    external:
      name: channels


